meta:
  environment: uaa-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: postgres
    networks:
      - name: uaa1
        static_ips: [10.244.2.2]
  - name: uaa
    networks:
      - name: uaa1
        static_ips: ~

properties:
  uaa:
    catalina_opts: -Xmx192m -XX:MaxPermSize=128m
    jwt:
      signing_key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIICXAIBAAKBgQDHFr+KICms+tuT1OXJwhCUmR2dKVy7psa8xzElSyzqx7oJyfJ1
        JZyOzToj9T5SfTIq396agbHJWVfYphNahvZ/7uMXqHxf+ZH9BL1gk9Y6kCnbM5R6
        0gfwjyW1/dQPjOzn9N394zd2FJoFHwdq9Qs0wBugspULZVNRxq7veq/fzwIDAQAB
        AoGBAJ8dRTQFhIllbHx4GLbpTQsWXJ6w4hZvskJKCLM/o8R4n+0W45pQ1xEiYKdA
        Z/DRcnjltylRImBD8XuLL8iYOQSZXNMb1h3g5/UGbUXLmCgQLOUUlnYt34QOQm+0
        KvUqfMSFBbKMsYBAoQmNdTHBaz3dZa8ON9hh/f5TT8u0OWNRAkEA5opzsIXv+52J
        duc1VGyX3SwlxiE2dStW8wZqGiuLH142n6MKnkLU4ctNLiclw6BZePXFZYIK+AkE
        xQ+k16je5QJBAN0TIKMPWIbbHVr5rkdUqOyezlFFWYOwnMmw/BKa1d3zp54VP/P8
        +5aQ2d4sMoKEOfdWH7UqMe3FszfYFvSu5KMCQFMYeFaaEEP7Jn8rGzfQ5HQd44ek
        lQJqmq6CE2BXbY/i34FuvPcKU70HEEygY6Y9d8J3o6zQ0K9SYNu+pcXt4lkCQA3h
        jJQQe5uEGJTExqed7jllQ0khFJzLMx0K6tj0NeeIzAaGCQz13oo2sCdeGRHO4aDh
        HH6Qlq/6UOV5wP8+GAcCQFgRCcB+hrje8hfEEefHcFpyKH+5g1Eu1k0mLrxK2zd+
        4SlotYRHgPCEubokb2S1zfZDWIXW3HmggnGgM949TlY=
        -----END RSA PRIVATE KEY-----
      verification_key: |
        -----BEGIN PUBLIC KEY-----
        MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDHFr+KICms+tuT1OXJwhCUmR2d
        KVy7psa8xzElSyzqx7oJyfJ1JZyOzToj9T5SfTIq396agbHJWVfYphNahvZ/7uMX
        qHxf+ZH9BL1gk9Y6kCnbM5R60gfwjyW1/dQPjOzn9N394zd2FJoFHwdq9Qs0wBug
        spULZVNRxq7veq/fzwIDAQAB
        -----END PUBLIC KEY-----
    cc:
      client_secret: cc-secret
    admin:
      client_secret: adminsecret
    batch:
      username: batch-username
      password: batch-password
    clients:
      <<: (( merge || nil ))
      admin:
        id: admin
        authorities: clients.admin,clients.read,clients.write,clients.secret,scim.read,scim.write,uaa.admin
        authorized-grant-types: client_credentials
        scope: uaa.none
        secret: adminsecret
      app:
        id: app
        name: The Ultimate Oauth App
        authorities: uaa.resource
        authorized-grant-types: password,implicit,authorization_code,client_credentials
        autoapprove:
          - openid
        scope: cloud_controller.read,cloud_controller.write,openid,password.write,scim.userids,organizations.acme
        secret: appclientsecret
        signup_redirect_url: http://localhost:8080/app/
        change_email_redirect_url: http://localhost:8080/app/
        invitation_redirect_url: http://localhost:8080/app/
      cf:
        id: cf
        authorities: uaa.none
        authorized-grant-types: implicit,password,refresh_token
        autoapprove: true
        scope: cloud_controller.read,cloud_controller.write,openid,password.write,scim.userids,cloud_controller.admin,scim.read,scim.write,doppler.firehose
      cloud_controller:
        authorities: uaa.resource,scim.read,scim.write,password.write
        authorized-grant-types: client_credentials
        resource-ids: none
        scope: scim.read,scim.write,password.write
        secret: cloudcontrollersecret
      dashboard:
        id: dashboard
        authorities: uaa.resource
        authorized-grant-types: authorization_code
        scope: dashboard.user,openid
        secret: dashboardsecret
      identity:
        id: identity
        authorities: scim.zones,zones.read,cloud_controller.read,uaa.resource,zones.write
        authorized-grant-types: authorization_code,client_credentials,refresh_token
        autoapprove: true
        scope: cloud_controller.admin,cloud_controller.read,cloud_controller.write,openid,zones.*.admin,zones.read,zones.write
        secret: identitysecret
      login:
        authorities: oauth.login,scim.write,clients.read,notifications.write,critical_notifications.write,emails.write,scim.userids,password.write
        authorized-grant-types: client_credentials,authorization_code
        autoapprove: true
        scope: openid,oauth.approvals
        secret: loginsecret
      notifications:
        id: notifications
        authorities: cloud_controller.admin,scim.read
        authorized-grant-types: client_credentials
        secret: notificationssecret
      doppler:
        secret: doppler-secret
      cloud_controller_username_lookup:
        secret: cloud-controller-username-lookup-secret
      gorouter:
        secret: gorouter-secret
    client:
      autoapprove:
        - cf
    user:
        authorities:
          - openid
          - scim.me
          - cloud_controller.read
          - cloud_controller.write
          - cloud_controller_service_permissions.read
          - password.write
          - scim.userids
          - uaa.user
          - approvals.me
          - oauth.approvals
    scim:
      groups: acme,acme.dev,acme.qa
      group_membership:
        - acme|acme.dev,acme.qa
        - acme.dev|marissa
      users:
        - admin|admin|scim.write,scim.read,openid,cloud_controller.admin,clients.read,clients.write,doppler.firehose
        - marissa|koala|marissa@test.org|Marissa|Bloggs|uaa.user
      userids_enabled: true
    no_ssl: true
    domain: uaas

  login_server:
    login:
      invitationsEnabled: true
    smtp:
      host: 3.39.76.31
      port: 2525

  uaadb:
    db_scheme: postgresql
    address: (( properties.databases.address ))
    port: 5524
    roles:
      - tag: admin
        name: uaaadmin
        password: admin
    databases:
      - tag: uaa
        name: uaadb
        citext: true

  databases:
    db_scheme: postgres
    address: (( jobs.postgres.networks.uaa1.static_ips.[0] ))
    port: 5524
    roles:
      - tag: admin
        name: ccadmin
        password: admin
      - tag: admin
        name: uaaadmin
        password: admin
    databases:
      - tag: cc
        name: ccdb
        citext: true
      - tag: uaa
        name: uaadb
        citext: true

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: uaa1
  # Assumes up to 5 VMs, including 1 static and 4 dynamic.
  # Plus 5 (double the size) unused IPs, due to BOSH bug/quirk.
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.2.0/30
    reserved:
    - 10.244.2.1
    static:
    - 10.244.2.2

  - cloud_properties:
      name: random
    range: 10.244.2.4/30
    reserved:
    - 10.244.2.5
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.8/30
    reserved:
    - 10.244.2.9
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.12/30
    reserved:
    - 10.244.2.13
    static:
    - 10.244.2.14
  - cloud_properties:
      name: random
    range: 10.244.2.16/30
    reserved:
    - 10.244.2.17
    static: []

  # Bonus double-sized network required due to BOSH oddity
  - cloud_properties:
      name: random
    range: 10.244.2.20/30
    reserved:
    - 10.244.2.21
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.24/30
    reserved:
    - 10.244.2.25
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.28/30
    reserved:
    - 10.244.2.29
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.32/30
    reserved:
    - 10.244.2.33
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.36/30
    reserved:
    - 10.244.2.37
    static: []
