meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: postgres
    templates:
    - name: postgres
      release: uaa
    instances: 1
    resource_pool: small_z1
    networks: (( merge ))
    persistent_disk: 10240
  - name: uaa
    templates:
    - name: uaa
      release: uaa
    instances: 1
    resource_pool: small_z1
    networks: (( merge ))

networks: (( merge ))

properties:
  uaa: (( merge ))
  login_server: ((merge))
  uaadb: (( merge ))

  databases: ~

